plugins {
    id 'com.replaymod.preprocess' version 'pre.12'
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
    id 'xyz.wagyourtail.jvmdowngrader' version '1.2.2' apply false
}

apply plugin: 'maven-publish'
apply plugin: 'com.github.johnrengelman.shadow'
apply plugin: 'xyz.wagyourtail.jvmdowngrader'

preprocess {
    def mc12101 = createNode("1.21.1", 12101, "yarn")
    def mc12100 = createNode("1.21", 12100, "yarn")
    def mc12006 = createNode("1.20.6", 12006, "yarn")
    def mc12005 = createNode("1.20.5", 12005, "yarn")
    def mc12004 = createNode("1.20.4", 12004, "yarn")
    def mc12002 = createNode("1.20.2", 12002, "yarn")
    def mc12001 = createNode("1.20.1", 12001, "yarn")
    def mc11904 = createNode("1.19.4", 11904, "yarn")
    def mc11802 = createNode("1.18.2", 11802, "yarn")
    def mc11800 = createNode("1.18", 11800, "yarn")
    def mc11701 = createNode("1.17.1", 11701, "yarn")
    def mc11605 = createNode("1.16.5", 11605, "yarn")

    mc12101.link(mc12100, null)
    mc12100.link(mc12006, null)
    mc12006.link(mc12005, null)
    mc12005.link(mc12004, null)
    mc12004.link(mc12002, null)
    mc12002.link(mc12001, null)
    mc12001.link(mc11904, null)
    mc11904.link(mc11802, file("versions/mapping-1.19.4-1.18.2.txt"))
    mc11802.link(mc11800, null)
    mc11800.link(mc11701, file("versions/mapping-1.18.2-1.17.1.txt"))
    mc11701.link(mc11605, file("versions/mapping-1.17.1-1.16.5.txt"))
}

loom {
    runs {
        client {
            client()
            setConfigName("Minecraft Client")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}

base {
    archivesName = project.archives_base_name
}

def mcVersion = file("versions/mainProject").text.trim()
def versionParts = mcVersion.tokenize('.').collect { it.toInteger() }
def mcVer = versionParts[0] * 10000 + versionParts[1] * 100 + (versionParts.size() > 2 ? versionParts[2] : 0)

version = "${mcVersion}-${project.mod_version}"
group = project.maven_group

    def mappingsVersions = [
            11605: "1.16.5+build.10",
            11701: "1.17.1+build.65",
            11800: "1.18+build.1",
            11802: "1.18.2+build.4",
            11904: "1.19.4+build.2",
            12001: "1.20.1+build.10",
            12002: "1.20.2+build.4",
            12004: "1.20.4+build.3",
            12005: "1.20.5+build.1",
            12006: "1.20.6+build.3",
            12100: "1.21+build.9",
            12101: "1.21.1+build.3",
    ]

def fabricApiVersions = [
            11605: "0.42.0+1.16",
            11701: "0.46.1+1.17",
            11800: "0.44.0+1.18",
            11802: "0.77.0+1.18.2",
            11904: "0.87.2+1.19.4",
            12001: "0.92.2+1.20.1",
            12002: "0.91.2+1.20.2",
            12004: "0.96.3+1.20.4",
            12005: "0.97.8+1.20.5",
            12006: "0.100.0+1.20.6",
            12100: "0.100.7+1.21",
            12101: "0.110.0+1.21.1",
    ]

def getJavaVersion = {
        if (mcVer >= 12006) {
            return JavaVersion.VERSION_21
        } else if (mcVer >= 11700) {
            return JavaVersion.VERSION_17
        }
        return JavaVersion.VERSION_1_8
    }

java {
    sourceCompatibility = getJavaVersion()
    targetCompatibility = getJavaVersion()
}

tasks.withType(JavaCompile).configureEach {
    options.release = getJavaVersion().majorVersion.toInteger()
    options.encoding = "UTF-8"
}

repositories {
    mavenCentral()
    maven {
        name = "MiranCZRepo"
        url = "https://mirancz.github.io/maven/"
        artifactUrls("https://mirancz.github.io/maven/cabaletta/baritone-unoptimized/${mcVersion}")
    }
    maven {
        name = 'babbaj-repo'
        url = 'https://babbaj.github.io/maven/'
    }
    flatDir {
        dirs '../baritone/dist'
    }
}

jvmdg {
    downgradeTo = getJavaVersion()
}

dependencies {
    minecraft("com.mojang:minecraft:${mcVersion}")
    mappings("net.fabricmc:yarn:${mappingsVersions[mcVer]}:v2")
    modImplementation("net.fabricmc:fabric-loader:${project.loader_version}")
    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.3.5")))

    modImplementation("net.fabricmc.fabric-api:fabric-api:${fabricApiVersions[mcVer]}")

    implementation 'com.fasterxml.jackson.core:jackson-core:2.16.0'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.16.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.16.0'

    include('xyz.wagyourtail.jvmdowngrader:jvmdowngrader-java-api:0.9.0:downgraded-8')

    implementation 'dev.babbaj:nether-pathfinder:1.5'

    shadow('com.fasterxml.jackson.core:jackson-core:2.16.0')
    shadow('com.fasterxml.jackson.core:jackson-annotations:2.16.0')
    shadow('com.fasterxml.jackson.core:jackson-databind:2.16.0')

    if (getProject().hasProperty("altoclef.development")) {
        modImplementation "baritone-api-fabric:baritone-unoptimized-fabric-${mcVersion}"
        include "baritone-api-fabric:baritone-unoptimized-fabric-${mcVersion}"
    } else {
        modImplementation "cabaletta:baritone-unoptimized-fabric:${mcVersion}"
        include "cabaletta:baritone-unoptimized-fabric:${mcVersion}"
    }
}

shadowJar {
    configurations = [project.configurations.shadow]
}

remapJar {
    dependsOn("shadowJar")
    input.set(shadowJar.archiveFile)
}

downgradeJar {
    dependsOn("remapJar")
    inputFile.set(remapJar.archiveFile)
}

tasks.register('replaceJar') {
    if (getJavaVersion() == targetCompatibility) {
        return
    }

    dependsOn downgradeJar
    doLast {
        def originalJar = tasks.remapJar.archiveFile.get().asFile
        def downgradedJar = file("${originalJar.parent}/${originalJar.name.replace('.jar', '-downgraded.jar')}")
        if (downgradedJar.exists()) {
            originalJar.delete()
            downgradedJar.renameTo(originalJar)
        } else {
            throw new GradleException("Downgraded JAR not found: ${downgradedJar}")
        }
    }
}

build {
    dependsOn tasks.replaceJar
}

processResources {
    inputs.property("version", project.version)
    inputs.property("mcVersion", mcVersion)

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "mcVersion": mcVersion
    }

    from(sourceSets.main.resources.srcDirs) {
        duplicatesStrategy DuplicatesStrategy.EXCLUDE
        exclude "fabric.mod.json"
    }
}

task sourcesJar(type: Jar, dependsOn: classes) {
    from sourceSets.main.allSource
}

jar {
    from "LICENSE"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact(remapJar) {
                builtBy remapJar
            }
            artifact(sourcesJar) {
                builtBy remapSourcesJar
            }
        }
    }
}
